repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-xml
      - id: check-json
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: fix-encoding-pragma
        args:
          - --ignore-case
          - --unique
  - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          args:
            - --max-line-length=88
            - --ignore=E203
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --multi-line=3
          - --src=cac_api
          - --src=tests
   - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3